#!/bin/bash

source orkhideya
ork_include qemu

export ORK_QEMU_ARGS=""$ORK_QEMU_ARGS" "$(qemu_arg_default "$ORK_QEMU_ARGS" name winxp)""
export ORK_QEMU_ARGS=""$ORK_QEMU_ARGS" "$(qemu_arg_default "$ORK_QEMU_ARGS" m 1g)""
export ORK_QEMU_ARGS=""$ORK_QEMU_ARGS" "$(qemu_arg_default "$ORK_QEMU_ARGS" hda "$(qemu_img_file "x86.windows.xp.base")")""
export ORK_QEMU_SYSTEM="qemu-system-i386"
