#!/bin/bash

source orkhideya
ork_include qemu
ork_include stdout

if [ -z "$ORK_QEMU_LABEL" ]; then
   stdout_error "No qemu label."
   exit 1
fi

if [ -z "$ORK_QEMU_IMAGE" ]; then
   stdout_error "No qemu image to fork."
   exit 2
fi

_new_image_file="$(qemu_img_file "$ORK_QEMU_IMAGE").${ORK_QEMU_LABEL}.fork"

if [ -e "$_new_image_file" ]; then
   shred -u "$_new_image_file"
fi
