#!/bin/bash

source orkhideya
ork_include qemu

export ORK_QEMU_ARGS=""$ORK_QEMU_ARGS" "$(qemu_arg_default "$ORK_QEMU_ARGS" name win7)""
export ORK_QEMU_ARGS=""$ORK_QEMU_ARGS" "$(qemu_arg_default "$ORK_QEMU_ARGS" m 2g)""

if [ "$ORK_QEMU_SYSTEM" == "qemu-system-i386" ]; then
   export ORK_QEMU_ARGS=""$ORK_QEMU_ARGS" "$(qemu_arg_default "$ORK_QEMU_ARGS" hda "$(qemu_img_file "x86.windows.7.base")")""
elif [ "$ORK_QEMU_SYSTEM" == "qemu-system-x86_64" ]; then
   export ORK_QEMU_ARGS=""$ORK_QEMU_ARGS" "$(qemu_arg_default "$ORK_QEMU_ARGS" hda "$(qemu_img_file "x86-64.windows.7.base")")""
fi
