#!/bin/bash 

source orkhideya
ork_include stdlib
ork_include stdout
ork_include qemu

_label="$1"
if [ -z "$_label" -o "$_label" == "-" ]; then
   _label="qemu-machine-x86_64"
fi

_args="${@:2}"

stdout_normal "Building commandline for $(stdout_color_wrap main-focused "x86_64") qemu machine."
_args=""$_args" "$(qemu_arg_default "$_args" "cpu" "kvm64")""

stdlib_trap qemu_vm_boot '' x86_64 "$_label" $_args

exit 0
