#!/bin/bash

source orkhideya
ork_include qemu
ork_include stdout

function diff_default_function
{
   local _base="$1"
   local _target="$2"

   diff -rq "$_base" "$_target"
   return 0 
}

if [ -z "$ORK_QEMU_LABEL" ]; then
   stdout_error "No qemu label."
   exit 1
fi

if [ -z "$ORK_QEMU_IMAGE" ]; then
   stdout_error "No forked qemu image."
   exit 2
fi

if [ -z "$ORK_QEMU_DISK_DIFF_FUNC" ]; then
   ORK_QEMU_DISK_DIFF_FUNC="diff_default_function"
fi

if [ -z "$ORK_QEMU_DISK_DIFF_FORK_DESTROY" ]; then
   ORK_QEMU_DISK_DIFF_FORK_DESTROY=1
fi

_base_image_file="$(qemu_img_file "$ORK_QEMU_IMAGE")"
_modded_image_file="${_base_image_file}.${ORK_QEMU_LABEL}.fork"
_diff_path="$(stdlib_tmpfile "${ORK_QEMU_LABEL}-${ORK_QEMU_IMAGE}-diff")"
_diff_base="$_diff_path/base"
_diff_target="$_diff_path/target"
_diff_file="$_diff_path/diff"

function diff_cleanup
{
   qemu_nbd_unmount "$_diff_base"
   qemu_nbd_unmount "$_diff_target"
}

stdlib_trap_cleanup_push 'diff_cleanup'

stdout_warning "Mounting $(stdout_color_wrap main-focused "$_base_image_file")."
stdlib_trap qemu_img_mount "$ORK_QEMU_IMAGE" "$_diff_base" -o ro

stdout_warning "Mounting $(stdout_color_wrap main-focused "$_diff_base")."
stdlib_trap qemu_nbd_mount "$_modded_image_file" "$_diff_target" -o ro

stdout_warning "Performing diff. This may take a while."
stdlib_trap $ORK_QEMU_DISK_DIFF_FUNC "$_diff_base" "$_diff_target" > "$_diff_file"

stdout_normal "Diff stored at $(stdout_color_wrap main-focused "$_diff_file")."
qemu_nbd_unmount "$_diff_base" && qemu_nbd_unmount "$_diff_target" && rm -r "$_diff_base" "$_diff_target"

if [ "$ORK_QEMU_DISK_DIFF_FORK_DESTROY" == "1" ]; then
   source "$(qemu_vm_shutdown_file disk.fork)"
fi
