#!/bin/bash

source orkhideya
ork_include if
ork_include stdlib

_tunnel_interface="$(cat "$(stdlib_tmpfile "${ORK_QEMU_LABEL}-tap")")"
if_class_destroy tunnel "$_tunnel_interface"
shred -u "$(stdlib_tmpfile "${ORK_QEMU_LABEL}-tap")"
